# Generated by Django 4.2.30 on 2026-06-18 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banking', '0004_userprofile_registration_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='location',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
